"""head

Revision ID: 09bf3d62a39f
Revises: 
Create Date: 2023-03-27 20:19:50.111285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09bf3d62a39f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("folder", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("extension", sa.String(length=100), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track")
    # ### end Alembic commands ###
