"""head

Revision ID: 0a1d983d0f37
Revises: 50ebea28889e
Create Date: 2024-07-03 13:23:25.870390

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a1d983d0f37"
down_revision = "50ebea28889e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["album.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("track") as batch_op:
        batch_op.add_column(sa.Column("album_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_track_album", "album", ["album_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track") as batch_op:
        batch_op.drop_constraint("fk_track_album", type_="foreignkey")
        batch_op.drop_column("album_id")
    op.drop_table("album")
    # ### end Alembic commands ###
