"""head

Revision ID: 418fa17db5cb
Revises: 8fa531e987ed
Create Date: 2023-08-27 17:07:57.951809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "418fa17db5cb"
down_revision = "8fa531e987ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("file_hash", sa.BINARY(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "file_hash")
    # ### end Alembic commands ###
