"""head

Revision ID: 50ebea28889e
Revises: 418fa17db5cb
Create Date: 2023-12-21 15:26:50.164480

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50ebea28889e"
down_revision = "418fa17db5cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track") as batch_op:
        batch_op.alter_column(
            "file_hash", existing_type=sa.NUMERIC(precision=32), nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track") as batch_op:
        batch_op.alter_column(
            "file_hash", existing_type=sa.NUMERIC(precision=32), nullable=True
        )
    # ### end Alembic commands ###
