"""head

Revision ID: f9d9d821799a
Revises: 09bf3d62a39f
Create Date: 2023-08-12 14:53:15.176922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9d9d821799a"
down_revision = "09bf3d62a39f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color_bytes", sa.BINARY(length=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_to_tags",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "tag_id"),
    )
    with op.batch_alter_table("track") as batch_op:
        batch_op.alter_column(
            "folder", existing_type=sa.VARCHAR(length=256), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "extension", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column("duration", existing_type=sa.FLOAT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track") as batch_op:
        batch_op.alter_column("duration", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column(
            "extension", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "folder", existing_type=sa.VARCHAR(length=256), nullable=True
        )
    op.drop_table("track_to_tags")
    op.drop_table("tag")
    # ### end Alembic commands ###
